v.008
io.reactivex.exceptions.OnErrorNotImplementedException: value precision
of 40 is greater than maximum iou precision of 16
	at
io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
	at
io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
	at
io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:74)
	at
io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:64)
	at
io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58)
	at
com.jakewharton.rxrelay2.PublishRelay$PublishDisposable.onNext(PublishRelay.java:176)
	at com.jakewharton.rxrelay2.PublishRelay.accept(PublishRelay.java:141)
	at
com.jakewharton.rxrelay2.AppendOnlyLinkedArrayList.accept(AppendOnlyLinkedArrayList.java:101)
	at
com.jakewharton.rxrelay2.SerializedRelay.emitLoop(SerializedRelay.java:73)
	at
com.jakewharton.rxrelay2.SerializedRelay.accept(SerializedRelay.java:58)
	at com.mbcu.mmm.rx.RxBus.send(RxBus.java:12)
	at
com.mbcu.mmm.main.WebSocketClient$1.onTextMessage(WebSocketClient.java:59)
	at
com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
	at
com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:260)
	at
com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:238)
	at
com.neovisionaries.ws.client.ReadingThread.handleContinuationFrame(ReadingThread.java:797)
	at
com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:743)
	at
com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at
com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at
com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
Caused by: com.ripple.core.coretypes.Amount$PrecisionError: value
precision of 40 is greater than maximum iou precision of 16
	at com.ripple.core.coretypes.Amount.initialize(Amount.java:148)
	at com.ripple.core.coretypes.Amount.setAndCheckValue(Amount.java:130)
	at com.ripple.core.coretypes.Amount.<init>(Amount.java:101)
	at com.ripple.core.coretypes.Amount.<init>(Amount.java:112)
	at com.ripple.core.coretypes.Amount.<init>(Amount.java:88)
	at com.mbcu.mmm.sequences.counters.Yuki.buildCounter(Yuki.java:90)
	at com.mbcu.mmm.sequences.counters.Yuki.lambda$1(Yuki.java:59)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.mbcu.mmm.sequences.counters.Yuki.counter(Yuki.java:49)
	at com.mbcu.mmm.sequences.counters.Yuki.lambda$0(Yuki.java:37)
	at
io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:60)
	... 16 more
Exception in thread "ReadingThread"
io.reactivex.exceptions.OnErrorNotImplementedException: value precision
of 40 is greater than maximum iou precision of 16
	at
io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
	at
io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
	at
io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:74)
	at
io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:64)
	at
io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58)
	at
com.jakewharton.rxrelay2.PublishRelay$PublishDisposable.onNext(PublishRelay.java:176)
	at com.jakewharton.rxrelay2.PublishRelay.accept(PublishRelay.java:141)
	at
com.jakewharton.rxrelay2.AppendOnlyLinkedArrayList.accept(AppendOnlyLinkedArrayList.java:101)
	at
com.jakewharton.rxrelay2.SerializedRelay.emitLoop(SerializedRelay.java:73)
	at
com.jakewharton.rxrelay2.SerializedRelay.accept(SerializedRelay.java:58)
	at com.mbcu.mmm.rx.RxBus.send(RxBus.java:12)
	at
com.mbcu.mmm.main.WebSocketClient$1.onTextMessage(WebSocketClient.java:59)
	at
com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
	at
com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:260)
	at
com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:238)
	at
com.neovisionaries.ws.client.ReadingThread.handleContinuationFrame(ReadingThread.java:797)
	at
com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:743)
	at
com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at
com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at
com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
Caused by: com.ripple.core.coretypes.Amount$PrecisionError: value
precision of 40 is greater than maximum iou precision of 16
	at com.ripple.core.coretypes.Amount.initialize(Amount.java:148)
	at com.ripple.core.coretypes.Amount.setAndCheckValue(Amount.java:130)
	at com.ripple.core.coretypes.Amount.<init>(Amount.java:101)
	at com.ripple.core.coretypes.Amount.<init>(Amount.java:112)
	at com.ripple.core.coretypes.Amount.<init>(Amount.java:88)
	at com.mbcu.mmm.sequences.counters.Yuki.buildCounter(Yuki.java:90)
	at com.mbcu.mmm.sequences.counters.Yuki.lambda$1(Yuki.java:59)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.mbcu.mmm.sequences.counters.Yuki.counter(Yuki.java:49)
	at com.mbcu.mmm.sequences.counters.Yuki.lambda$0(Yuki.java:37)
	at
io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:60)
	... 16 more